kind: Job
apiVersion: batch/v1
metadata:
  name: gan-eval
spec:
  template:
    spec:
      containers:
      - name: gan-eval
        image: "tensorflow/tensorflow:2.2.0-gpu"
        workingDir: /storage/experiments
        command:
        - sh
        - eval_inception.sh
        resources:
          limits:
            memory: 32Gi
            cpu: 8
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
