kind: Job
apiVersion: batch/v1
metadata:
  name: gan-gen-nemo
spec:
  template:
    spec:
      containers:
      - name: gan-gen-nemo
        image: "tensorflow/tensorflow:latest-gpu-py3"
        workingDir: /storage/experiments
        command:
        - sh
        - generate_images.sh
        resources:
          limits:
            memory: 16Gi
            cpu: 4
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
