kind: Job
apiVersion: batch/v1
metadata:
  name: gan-train-nemo
spec:
  template:
    spec:
      containers:
      - name: gan-train-nemo
        image: "tensorflow/tensorflow:latest-gpu-py3"
        workingDir: /storage/experiments
        command:
        - sh
        - nemo_conditional_train.sh
        resources:
          limits:
            memory: 32Gi
            cpu: 8
            nvidia.com/gpu: 2
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
